# Generated by Django 4.1.4 on 2023-01-07 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(default='0000', max_length=100)),
                ('name', models.CharField(default='name', max_length=100)),
                ('published_at', models.DateTimeField(default=datetime.datetime(2023, 1, 7, 14, 57, 31, 74972))),
                ('description', models.TextField(blank=True, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
