# Generated by Django 4.1.4 on 2023-01-07 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancymodel',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 15, 10, 47, 625508)),
        ),
    ]
