# Generated by Django 4.1.4 on 2023-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographypage',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='img'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='img'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='img'),
        ),
        migrations.AddField(
            model_name='skillspage',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='img'),
        ),
    ]
