# Generated by Django 4.1.4 on 2023-01-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancymodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='key_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
