# Generated by Django 4.1.4 on 2023-01-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_geographypage_image_homepage_image_infopage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ImageField(default=None, upload_to='homepage', verbose_name='img'),
        ),
    ]
