# Generated by Django 4.1.4 on 2023-01-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vacancymodel_address_vacancymodel_key_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancymodel',
            name='employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
