# Generated by Django 4.1.4 on 2023-01-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_homepage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infopage',
            old_name='image',
            new_name='graph_left',
        ),
        migrations.AddField(
            model_name='infopage',
            name='graph_right',
            field=models.ImageField(default=None, upload_to='', verbose_name='img'),
        ),
    ]
