# Generated by Django 4.1.4 on 2023-01-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_image_infopage_graph_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='graph_left',
            field=models.ImageField(default=None, upload_to='', verbose_name='Левый график'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='graph_right',
            field=models.ImageField(default=None, upload_to='', verbose_name='Правый график'),
        ),
    ]
