# Generated by Django 4.1.4 on 2023-01-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_infopage_graph_left_alter_infopage_graph_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographypage',
            name='title',
            field=models.CharField(default='geographyPage', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='homepage', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title',
            field=models.CharField(default='infopage', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='skillspage',
            name='title',
            field=models.CharField(default='skillsPage', max_length=100, verbose_name='Заголовок'),
        ),
    ]
