# Generated by Django 4.1.4 on 2023-01-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_geographypage_title_alter_homepage_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographypage',
            name='text',
        ),
        migrations.AddField(
            model_name='geographypage',
            name='text_1',
            field=models.TextField(default=None, verbose_name='Первый заголовок'),
        ),
        migrations.AddField(
            model_name='geographypage',
            name='text_2',
            field=models.TextField(default=None, verbose_name='Второй заголовок'),
        ),
    ]
