# Generated by Django 4.1.4 on 2023-01-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_geographypage_text_geographypage_text_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographypage',
            name='table_3',
        ),
        migrations.RemoveField(
            model_name='geographypage',
            name='table_4',
        ),
        migrations.AlterField(
            model_name='geographypage',
            name='table_1',
            field=models.TextField(default=None, verbose_name='Таблицы для IT'),
        ),
        migrations.AlterField(
            model_name='geographypage',
            name='table_2',
            field=models.TextField(default=None, verbose_name='Таблицы для DevOps'),
        ),
    ]
