# Generated by Django 4.1.4 on 2023-01-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_geographypage_table_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographypage',
            name='image',
        ),
    ]
