# Generated by Django 4.1.4 on 2023-01-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_geographypage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillspage',
            name='image',
        ),
        migrations.AlterField(
            model_name='infopage',
            name='graph_left',
            field=models.ImageField(default=None, upload_to='infopage', verbose_name='Левый график'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='graph_right',
            field=models.ImageField(default=None, upload_to='infopage', verbose_name='Правый график'),
        ),
    ]
